{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-python.serviceAccountName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
