apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: python-app-set
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesFile: values-dev.yaml
            autoSync: true
          - env: prod
            namespace: prod
            valuesFile: values-prod.yaml
            autoSync: false
  template:
    metadata:
      name: "python-appset-{{ .env }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/samerspc/DevOps-Core-Course.git
        targetRevision: master
        path: k8s/app-python
        helm:
          valueFiles:
            - "{{ .valuesFile }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if .autoSync }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
    {{- end }}
